### ISSUE TITLE
gcc 6.40 needs to have libssp disabled

### ISSUE THREAD

**Issue by JPeterMugaas** [Alexpux/MSYS2-packages#1136]
The GCC 6.40 compiler needs "--disable-libssp" instead of "--enable-libssp".  See: https://www.mail-archive.com/cygwin@cygwin.com/msg155191.html .

The thing is that the newlib 3.0.0 (part of the cygwin 2.10 release) includes a SSP implementation.

That might be causing issues like this when compiling rhash from git which had worked before installing newlib 3.0.0. 

===
/bin/sh -e ./tty/MKexpanded.sh "gcc -E" -DHAVE_CONFIG_H -I../ncurses -I. -I../include -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -DNDEBUG > expanded.c
/bin/sh -e ./tinfo/MKfallback.sh /usr/share/terminfo ../misc/terminfo.src /usr/bin/tic  >fallback.c
In file included from /usr/include/stdlib.h:338:0,
                 from ../ncurses/build.priv.h:60,
                 from ./tinfo/make_hash.c:40:
/usr/include/ssp/stdlib.h:9:20: error: expected declaration specifiers or ‘...’ before ‘mbstowcs’
 __ssp_decl(size_t, mbstowcs, (wchar_t *__buf, const char *__src, size_t __n))
                    ^~~~~~~~
/usr/include/ssp/stdlib.h:9:30: error: expected declaration specifiers or ‘...’ before ‘(’ token
 __ssp_decl(size_t, mbstowcs, (wchar_t *__buf, const char *__src, size_t __n))
                              ^
/usr/include/ssp/stdlib.h:16:28: error: expected declaration specifiers or ‘...’ before ‘wcstombs’
 __ssp_redirect_raw(size_t, wcstombs, \
                            ^~~~~~~~
/usr/include/ssp/stdlib.h:17:5: error: expected declaration specifiers or ‘...’ before ‘(’ token
     (char *__buf, const wchar_t *__src, size_t __len), \
     ^
/usr/include/ssp/stdlib.h:18:5: error: expected declaration specifiers or ‘...’ before ‘(’ token
     (__buf, __src, __len), __buf != NULL, __ssp_bos);
     ^
/usr/include/ssp/stdlib.h:18:28: error: unknown type name ‘__buf’
     (__buf, __src, __len), __buf != NULL, __ssp_bos);
                            ^~~~~
/usr/include/ssp/stdlib.h:18:43: error: unknown type name ‘__ssp_bos’
     (__buf, __src, __len), __buf != NULL, __ssp_bos);
                                           ^~~~~~~~~
/usr/include/ssp/stdlib.h:20:17: error: expected declaration specifiers or ‘...’ before ‘wctomb’
 __ssp_decl(int, wctomb, (char *__buf, wchar_t __wc))
                 ^~~~~~
/usr/include/ssp/stdlib.h:20:25: error: expected declaration specifiers or ‘...’ before ‘(’ token
 __ssp_decl(int, wctomb, (char *__buf, wchar_t __wc))
                         ^
In file included from /usr/include/string.h:180:0,
                 from ../ncurses/build.priv.h:61,
                 from ./tinfo/make_hash.c:40:
/usr/lib/gcc/x86_64-pc-msys/6.4.0/include/ssp/string.h:38:17: fatal error: ssp.h: No such file or directory
 #include <ssp.h>
                 ^
compilation terminated.
make[1]: *** [Makefile:241: make_hash.exe] Error 1
===
BTW, I am now working on the cygwin-2.10 release tag to get that compiled instead of the newlib 3.0.0 tag.  That might be better because that includes a catgets facility and uses newer code from newlib.

**Comment by Alexpux** [comment]
msys2-runtime already 2.10.0 and GCC builded without libssp
