### ISSUE TITLE
itstool: v2.0.4 - unable build gtk-doc

### ISSUE THREAD

**Issue by vyache-slav** [Alexpux/MSYS2-packages#1380]
after updating itstool from 2.0.2-2 to 2.0.4-1 build gtk-doc fail.
(MSYS, MINGW32)

sometimes got:

> Error: Could not merge translations:
> 'NoneType' object has no attribute '__getitem__'
> make[2]: *** [Makefile:524: cs/cs.stamp] Error 1
> make[2]: *** Waiting for unfinished jobs....

sometimes:

> Making all in manual
> make[1]: Entering directory '/var/altdev-build-msys/gtk-doc/src/build-i686-pc-msys/help/manual'
>   GEN      bn_IN/bn_IN.mo
>   GEN    bn_IN/
>   GEN      cs/cs.mo
>   GEN    cs/
>   GEN      de/de.mo
>   GEN    de/
>   GEN      el/el.mo
>   GEN    el/
>   GEN      en_GB/en_GB.mo
>   GEN    en_GB/
>   GEN      es/es.mo
>   GEN    es/
>   GEN      fr/fr.mo
>   GEN    fr/
> /bin/sh: line 4:  2324 Segmentation fault      (core dumped) itstool -m "${mo}" ${d}/C/index.docbook ${d}/C/fdl-appendix.xml
> make[1]: *** [Makefile:524: fr/fr.stamp] Error 139
> make[1]: Leaving directory '/var/altdev-build-msys/gtk-doc/src/build-i686-pc-msys/help/manual'
> make: *** [Makefile:371: all-recursive] Error 1
> 
rollback to 2.0.2-2 and successfull build gtk-doc

**Comment by vyache-slav** [comment]
now everything is fine, but (offtop):
>```
> Making check in docs
> make[3]: Entering directory '/var/altdev-build-msys/gtk-doc/src/build-i686-pc-msys/tests/bugs/docs'
> make  check-local
> make[4]: Entering directory '/var/altdev-build-msys/gtk-doc/src/build-i686-pc-msys/tests/bugs/docs'
>   DOC   Preparing build
>   DOC   00:00:00.403049400: Scanning header files
>   DOC   00:00:01.666741000: Building XML
> ../../../../gtk-doc-1.28/tests/bugs/src/tester.h:562: warning: Stability level for BUG_791928 is UndefinedTestValue. It should be one of these: Stable, Unstable, or Private.
>   DOC   00:00:02.672371100: Building HTML
>   DOC   00:00:07.512231200: Fixing cross-references
> Traceback (most recent call last):
>   File "/var/altdev-build-msys/gtk-doc/src/build-i686-pc-msys/gtkdoc-fixxref", line 57, in <module>
>     fixxref.Run(options)
>   File "/var/altdev-build-msys/gtk-doc/src/gtk-doc-1.28/gtkdoc/fixxref.py", line 64, in Run
>     FixCrossReferences(options.module_dir, options.module, options.src_lang)
>   File "/var/altdev-build-msys/gtk-doc/src/gtk-doc-1.28/gtkdoc/fixxref.py", line 224, in FixCrossReferences
>     FixHTMLFile(src_lang, module, full_entry)
>   File "/var/altdev-build-msys/gtk-doc/src/gtk-doc-1.28/gtkdoc/fixxref.py", line 247, in FixHTMLFile
>     repl_func, content, flags=re.DOTALL)
>   File "/usr/lib/python2.7/re.py", line 155, in sub
>     return _compile(pattern, flags).sub(repl, string, count)
>   File "/var/altdev-build-msys/gtk-doc/src/gtk-doc-1.28/gtkdoc/fixxref.py", line 244, in repl_func
>     return HighlightSource(src_lang, m.group(1), m.group(2))
>   File "/var/altdev-build-msys/gtk-doc/src/gtk-doc-1.28/gtkdoc/fixxref.py", line 354, in HighlightSource
>     [config.highlight] + shlex.split(highlight_options) + [temp_source_file]).decode('utf-8')
>   File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> 
>```
 when  configure gtk-doc need to use --with-highlight=no (as in mingw-gtk-doc) or make some changes in gtkdoc/fixxref.py
[a001-src-highlight.patch.gz](https://github.com/Alexpux/MSYS2-packages/files/2293014/a001-src-highlight.patch.gz)

(for mingw --with-highlight=source-highlight)
