### ISSUE TITLE
Eigen compilation error with gcc 8.2.1 on MSYS2

### ISSUE THREAD

**Issue by jdtournier** [Alexpux/MSYS2-packages#1530]
I'd originally [posted this on StackOverflow](https://stackoverflow.com/q/53842888/3244166), but I'm not sure the MSYS2 developers are monitoring that forum (?). I'm reproducing my post here, with apologies for the duplication.

---

We are [facing errors][1] compiling against Eigen 3.3.7 (and probably older versions) against the latest versions of GCC 8.2.1 supplied by MSYS2. Strangely, this only happens with the latest builds of the same package (`mingw-w64-x86_64-gcc` 8.2.1):

- 8.2.1+20181123-1 : fine
- 8.2.1+20181130-1 : error
- 8.2.1+20181207-1 : error

The error is:

    In file included from C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/SparseCore:50,
                     from C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/Sparse:26,
                     from C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/Eigen:2,
                     from src/registration/transform/search.h:21,
                     from src/registration/transform/initialiser_helpers.cpp:20:
    C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/src/SparseCore/SparseBlock.h: In member function 'Eigen::internal::sparse_matrix_block_impl<SparseMatrixType, BlockRows, BlockCols>::BlockType& Eigen::internal::sparse_matrix_block_impl<SparseMatrixType, BlockRows, BlockCols>::operator=(const BlockType&)':
    C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/src/SparseCore/SparseBlock.h:216:33: error: expected primary-expression before '>' token
           return operator=<BlockType>(other);

                                 ^

I'm assuming this is a bug in the GCC package supplied by MSYS2, rather than Eigen (the `SparseBlock.h` file hasn't changed for a while, as far as I can tell). Are the different GCC builds based on the same source code? Any idea what the issue might be?

--- 

EDIT: here is a MCVE:

**test.cpp:**

    #include <Eigen/Eigen>
    int main () { return 0; }

**compile with g++ 8.2.1 (version 8.2.1+20181130-1 or newer - no error with older version):**

    $ g++ $(pkg-config --cflags eigen3) test.cpp -o test
    In file included from C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/SparseCore:50,
                     from C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/Sparse:26,
                     from C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/Eigen:2,
                     from test.cpp:1:
    C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/src/SparseCore/SparseBlock.h: In member function 'Eigen::internal::sparse_matrix_block_impl<SparseMatrixType, BlockRows, BlockCols>::BlockType& Eigen::internal::sparse_matrix_block_impl<SparseMatrixType, BlockRows, BlockCols>::operator=(const BlockType&)':
    C:/Users/donald/msys64/mingw64/include/eigen3/Eigen/src/SparseCore/SparseBlock.h:216:33: error: expected primary-expression before '>' token
           return operator=<BlockType>(other);
                                     ^

  [1]: https://github.com/MRtrix3/mrtrix3/issues/1521

**Comment by Alexpux** [comment]
@jdtournier yeah this is seems GCC bug. Please report it to GCC bugzilla and provide here link for bugreport

**Comment by jdtournier** [comment]
OK, will do. Can I first confirm that the different builds (`8.2.1+20181123-1` & `8.2.1+20181130-1`) of the _same_ version of GCC 8.2.1 are actually compiled from different versions of the source code? I was assuming that these were all built from the same source tree, but maybe with different packaging tweaks or other modifications...

**Comment by Alexpux** [comment]
This builds are builded from different date snapshots of gcc

**Comment by jdtournier** [comment]
Bug report submitted to GCC Bugzilla:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88564

Thanks!

**Comment by jdtournier** [comment]
The feedback on the bug report is that things seems to work using the latest snapshot. I've looked at the history, and there are indeed a couple of relevant changes that would seem to match the symptoms and the dates - see the [GCC Bugzilla for details](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88564#c3). But to cut a long story short: there's a good chance the issue is already fixed at source. Would it be possible to update the package with the latest snapshot?

**Comment by Alexpux** [comment]
Will try to do on weekends

**Comment by jdtournier** [comment]
@Alexpux Thank you! Confirmed on my end too. Really appreciate the fast turnaround!
